import { db } from './firebase-config.js';
import { collection, addDoc, serverTimestamp } from 'https://www.gstatic.com/firebasejs/10.12.0/firebase-firestore.js';
import { getMultipleStockImages } from './stock-images.js';

const MOCK_PROPERTIES = [
  {
    title: "Premium 3BHK Apartment in OMR",
    description: "Spacious 3BHK apartment in a gated community on Old Mahabalipuram Road. Close to IT parks, schools, and hospitals. 24/7 security, covered parking, and modern amenities.",
    price: 9500000,
    location: "OMR, Chennai",
    address: "Block C, Prestige Lakeside Habitat, Thoraipakkam, OMR, Chennai 600097",
    area: 1450,
    landArea: 0,
    landRate: 6552,
    bedrooms: 3,
    bathrooms: 2,
    type: "flat",
    status: "sale",
    furnishing: "semiFurnished",
    amenities: ["Parking", "Lift", "Security", "Gym", "Swimming Pool", "Power Backup", "CCTV", "Clubhouse"],
    ownerName: "Rajesh Kumar",
    ownerPhone: "+91 98765 43210"
  },
  {
    title: "Independent House in Anna Nagar",
    description: "Well-maintained independent house in the heart of Anna Nagar. Ground + 1 floor with terrace. Prime location near bus stops and metro station.",
    price: 25000000,
    location: "Anna Nagar, Chennai",
    address: "12, 3rd Avenue, Anna Nagar West, Chennai 600040",
    area: 2200,
    landArea: 1800,
    landRate: 13889,
    bedrooms: 4,
    bathrooms: 3,
    type: "house",
    status: "sale",
    furnishing: "fullyFurnished",
    amenities: ["Parking", "Garden", "Power Backup", "Water Supply", "Rain Water Harvesting"],
    ownerName: "Lakshmi Narayanan",
    ownerPhone: "+91 94445 12345"
  },
  {
    title: "Luxury Villa in ECR",
    description: "Stunning sea-facing villa on East Coast Road with private garden, swimming pool, and modern interiors. Perfect weekend getaway or permanent residence.",
    price: 45000000,
    location: "ECR, Chennai",
    address: "Plot 45, Beach Villas, Muttukadu, ECR, Chennai 603112",
    area: 3500,
    landArea: 4000,
    landRate: 11250,
    bedrooms: 5,
    bathrooms: 4,
    type: "villa",
    status: "sale",
    furnishing: "fullyFurnished",
    amenities: ["Parking", "Swimming Pool", "Garden", "Security", "Power Backup", "CCTV", "Clubhouse"],
    ownerName: "Arun Vijay",
    ownerPhone: "+91 90000 11111"
  },
  {
    title: "2BHK Flat for Rent in Adyar",
    description: "Comfortable 2BHK apartment available for rent in Adyar, close to IIT Madras and Adyar bus depot. Well-ventilated with balcony. Vegetarian family preferred.",
    price: 22000,
    location: "Adyar, Chennai",
    address: "Flat 3B, Srinivasa Apartments, Lattice Bridge Road, Adyar, Chennai 600020",
    area: 950,
    landArea: 0,
    landRate: 0,
    bedrooms: 2,
    bathrooms: 1,
    type: "flat",
    status: "rent",
    furnishing: "semiFurnished",
    amenities: ["Parking", "Lift", "Water Supply", "Power Backup"],
    ownerName: "Meena Sundaram",
    ownerPhone: "+91 98411 56789"
  },
  {
    title: "Residential Plot in Saravanampatti",
    description: "DTCP approved residential plot in a well-developed area of Saravanampatti, Coimbatore. Close to IT corridor, schools, and shopping centers. Ready for construction.",
    price: 3600000,
    location: "Saravanampatti, Coimbatore",
    address: "Survey No. 234, Saravanampatti, Coimbatore 641035",
    area: 1200,
    landArea: 1200,
    landRate: 3000,
    bedrooms: 0,
    bathrooms: 0,
    type: "plot",
    status: "sale",
    furnishing: "unfurnished",
    amenities: [],
    ownerName: "Ganesh Moorthy",
    ownerPhone: "+91 94433 22110"
  },
  {
    title: "Modern 3BHK in RS Puram",
    description: "Brand new 3BHK apartment in RS Puram, Coimbatore's prime locality. Walking distance to market, temples, and restaurants. Premium fittings and spacious rooms.",
    price: 8500000,
    location: "RS Puram, Coimbatore",
    address: "Arun Heights, DB Road, RS Puram, Coimbatore 641002",
    area: 1350,
    landArea: 0,
    landRate: 6296,
    bedrooms: 3,
    bathrooms: 2,
    type: "flat",
    status: "sale",
    furnishing: "unfurnished",
    amenities: ["Parking", "Lift", "Security", "Power Backup", "Water Supply", "Intercom"],
    ownerName: "Priya Rajan",
    ownerPhone: "+91 97899 44556"
  },
  {
    title: "Commercial Space in Madurai",
    description: "Prime commercial office space on Bypass Road, Madurai. Ideal for IT companies, showrooms, or clinics. Ground floor with road-facing visibility.",
    price: 12000000,
    location: "Bypass Road, Madurai",
    address: "No. 78, Bypass Road, K. Pudur, Madurai 625007",
    area: 1800,
    landArea: 2000,
    landRate: 6000,
    bedrooms: 0,
    bathrooms: 2,
    type: "commercial",
    status: "sale",
    furnishing: "unfurnished",
    amenities: ["Parking", "Lift", "Power Backup", "Fire Safety", "CCTV"],
    ownerName: "Vel Murugan",
    ownerPhone: "+91 94873 11223"
  },
  {
    title: "Farm House near Ooty",
    description: "Beautiful 2-acre farm house near Ooty with lush greenery, fruit orchards, and mountain views. Perfect for holidays and retirement living.",
    price: 35000000,
    location: "Coonoor, Nilgiris",
    address: "Tiger Hill Estate, Coonoor Road, Nilgiris 643101",
    area: 2800,
    landArea: 87120,
    landRate: 402,
    bedrooms: 3,
    bathrooms: 2,
    type: "farmHouse",
    status: "sale",
    furnishing: "fullyFurnished",
    amenities: ["Parking", "Garden", "Water Supply", "Power Backup", "Security"],
    ownerName: "Karthik Subramanian",
    ownerPhone: "+91 96005 77889"
  },
  {
    title: "1BHK PG in Velachery",
    description: "Fully furnished 1BHK PG accommodation near Phoenix Mall, Velachery. Includes Wi-Fi, meals, housekeeping. Best for working professionals.",
    price: 12000,
    location: "Velachery, Chennai",
    address: "No. 45, Vijayaraghava Road, Velachery, Chennai 600042",
    area: 400,
    landArea: 0,
    landRate: 0,
    bedrooms: 1,
    bathrooms: 1,
    type: "flat",
    status: "pg",
    furnishing: "fullyFurnished",
    amenities: ["Security", "Power Backup", "Water Supply", "Maintenance Staff"],
    ownerName: "Deepa Nagaraj",
    ownerPhone: "+91 99621 33445"
  },
  {
    title: "4BHK Duplex in Trichy",
    description: "Spacious 4BHK duplex house in Woraiyur, Trichy. Double-height living room, modular kitchen, car parking. Near Trichy Junction and BHEL.",
    price: 11000000,
    location: "Woraiyur, Trichy",
    address: "Plot 12, Kumaran Nagar, Woraiyur, Trichy 620003",
    area: 2400,
    landArea: 1600,
    landRate: 6875,
    bedrooms: 4,
    bathrooms: 3,
    type: "house",
    status: "sale",
    furnishing: "semiFurnished",
    amenities: ["Parking", "Garden", "Power Backup", "Water Supply", "Rain Water Harvesting"],
    ownerName: "Senthil Kumar",
    ownerPhone: "+91 97517 88990"
  },
  {
    title: "Agricultural Land in Thanjavur",
    description: "6 acres of fertile agricultural land in Thanjavur delta region. Ideal for paddy cultivation or farm investment. Water canal access available.",
    price: 18000000,
    location: "Thanjavur",
    address: "Survey No. 456, Orathanadu Road, Thanjavur 613004",
    area: 261360,
    landArea: 261360,
    landRate: 69,
    bedrooms: 0,
    bathrooms: 0,
    type: "land",
    status: "sale",
    furnishing: "unfurnished",
    amenities: [],
    ownerName: "Bala Krishnan",
    ownerPhone: "+91 94421 55667"
  },
  {
    title: "2BHK Flat for Lease in Tambaram",
    description: "Well-maintained 2BHK flat for lease in Tambaram East. Close to railway station, schools, and supermarkets. 11-month lease with security deposit.",
    price: 600000,
    location: "Tambaram, Chennai",
    address: "Flat 2A, Ganesh Apartments, Tambaram East, Chennai 600059",
    area: 850,
    landArea: 0,
    landRate: 0,
    bedrooms: 2,
    bathrooms: 1,
    type: "flat",
    status: "lease",
    furnishing: "unfurnished",
    amenities: ["Parking", "Water Supply", "Power Backup"],
    ownerName: "Kavitha Devi",
    ownerPhone: "+91 98840 22334"
  },
  {
    title: "Luxury Penthouse in T. Nagar",
    description: "Exclusive penthouse apartment in T. Nagar with panoramic city views. Private terrace, Italian marble flooring, and smart home features.",
    price: 32000000,
    location: "T. Nagar, Chennai",
    address: "Top Floor, Prestige Tower, Thyagaraja Road, T. Nagar, Chennai 600017",
    area: 3200,
    landArea: 0,
    landRate: 10000,
    bedrooms: 4,
    bathrooms: 4,
    type: "flat",
    status: "sale",
    furnishing: "fullyFurnished",
    amenities: ["Parking", "Lift", "Security", "Gym", "Swimming Pool", "Power Backup", "CCTV", "Clubhouse", "Intercom", "Fire Safety"],
    ownerName: "Anand Krishnamurthy",
    ownerPhone: "+91 90030 55667"
  },
  {
    title: "3BHK Villa in Salem",
    description: "Beautiful independent villa in Salem with modern architecture. Vastu-compliant design, modular kitchen, and landscaped garden.",
    price: 7200000,
    location: "Fairlands, Salem",
    address: "No. 22, Green Valley Layout, Fairlands, Salem 636016",
    area: 1800,
    landArea: 2400,
    landRate: 3000,
    bedrooms: 3,
    bathrooms: 2,
    type: "villa",
    status: "sale",
    furnishing: "semiFurnished",
    amenities: ["Parking", "Garden", "Power Backup", "Water Supply", "Rain Water Harvesting"],
    ownerName: "Mani Vannan",
    ownerPhone: "+91 94882 11223"
  },
  {
    title: "Office Space for Rent in Tidel Park",
    description: "Plug-and-play office space for rent near Tidel Park, Taramani. 50 workstations, server room, pantry, and conference room. Ideal for startups.",
    price: 85000,
    location: "Taramani, Chennai",
    address: "3rd Floor, Olympia Tech Park, SIDCO Industrial Estate, Taramani, Chennai 600113",
    area: 2500,
    landArea: 0,
    landRate: 0,
    bedrooms: 0,
    bathrooms: 3,
    type: "commercial",
    status: "rent",
    furnishing: "fullyFurnished",
    amenities: ["Parking", "Lift", "Security", "Power Backup", "Fire Safety", "CCTV", "Maintenance Staff"],
    ownerName: "Tech Realty Solutions",
    ownerPhone: "+91 44 4560 1234"
  }
];

export async function seedProperties() {
  const propertiesRef = collection(db, 'properties');
  let count = 0;

  for (const prop of MOCK_PROPERTIES) {
    const images = getMultipleStockImages(prop.type, 3);
    const docData = {
      ...prop,
      images,
      coordinates: { latitude: 0, longitude: 0 },
      ownerId: 'seed-data',
      additionalDetails: {},
      createdAt: serverTimestamp(),
      updatedAt: serverTimestamp()
    };

    await addDoc(propertiesRef, docData);
    count++;
    console.log(`Seeded property ${count}/${MOCK_PROPERTIES.length}: ${prop.title}`);
  }

  console.log(`Done! Seeded ${count} properties.`);
  return count;
}
